# Generated by Django 3.2.3 on 2022-10-06 14:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0017_auto_20221006_1100'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id_order', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(default=datetime.datetime(2022, 10, 6, 11, 0, 21, 697660), verbose_name='Fecha')),
                ('state', models.CharField(choices=[('PEND', 'Pendiente'), ('ENTR', 'Entregado'), ('CANC', 'Cancelado')], default='PEND', max_length=4, verbose_name='Estado')),
                ('pickup_time', models.TimeField(choices=[(datetime.time(11, 30), '11:30'), (datetime.time(12, 0), '12:00'), (datetime.time(12, 30), '12:30'), (datetime.time(13, 0), '13:00'), (datetime.time(13, 30), '13:30')], default=1, verbose_name='Hora de retiro')),
                ('total_price', models.FloatField(default=0, verbose_name='Precio Total')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='OrderFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.food', verbose_name='Comida')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.order', verbose_name='Número de pedido')),
            ],
        ),
    ]
