# Generated by Django 3.2.3 on 2022-11-13 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0018_auto_20221112_1922'),
        ('customer', '0002_alter_order_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='items', through='customer.OrderFood', to='administrator.Food'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 13, 17, 54, 38, 175189), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='orderfood',
            name='quantity',
            field=models.PositiveIntegerField(choices=[('Uno', 1), ('Dos', 2), ('Tres', 3)], default=1, verbose_name='Cantidad'),
        ),
    ]
