# Generated by Django 3.2.3 on 2022-11-14 00:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0018_auto_20221112_1922'),
        ('customer', '0003_auto_20221113_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 13, 21, 12, 14, 831287), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='orderfood',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.food', verbose_name='Comida'),
        ),
    ]
