# Generated by Django 3.2.3 on 2022-11-14 20:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20221113_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 14, 17, 48, 51, 906827), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='orderfood',
            name='quantity',
            field=models.PositiveIntegerField(choices=[(1, 1), (1, 2), (1, 3)], default=1, verbose_name='Seleccionar'),
        ),
    ]
