# Generated by Django 3.2.3 on 2022-11-15 03:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0018_auto_20221112_1922'),
        ('customer', '0006_auto_20221114_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 0, 39, 7, 991351), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='orderfood',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.food', verbose_name='Comida'),
        ),
        migrations.AlterField(
            model_name='orderfood',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.order', verbose_name='Número de pedido'),
        ),
        migrations.AlterField(
            model_name='orderfood',
            name='quantity',
            field=models.PositiveIntegerField(choices=[(1, 1), (1, 2), (1, 3)], verbose_name='Elegir cantidad'),
        ),
    ]
