# Generated by Django 3.2.3 on 2022-11-15 03:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20221115_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 0, 42, 6, 38722), verbose_name='Fecha'),
        ),
    ]
