# Generated by Django 3.2.3 on 2022-11-15 03:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_order_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 0, 44, 2, 427788), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='orderfood',
            name='quantity',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3)], verbose_name='Elegir cantidad'),
        ),
    ]
