# Generated by Django 3.2.3 on 2022-09-24 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='PriceFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Fecha inicio')),
                ('price', models.FloatField(verbose_name='Precio')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id_food', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45, verbose_name='Nombre')),
                ('description', models.CharField(max_length=100, verbose_name='Descripción')),
                ('available', models.BooleanField(verbose_name='Disponible')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.pricefood')),
            ],
        ),
    ]
