# Generated by Django 3.2.3 on 2022-09-25 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_auto_20220925_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.food', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='pricefood',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.food', verbose_name='Comida'),
        ),
    ]
