# Generated by Django 3.2.3 on 2022-09-25 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_auto_20220925_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.food', verbose_name='Categoría'),
        ),
    ]
