# Generated by Django 3.2.3 on 2022-09-26 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_auto_20220925_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.ForeignKey(choices=[], null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.category', verbose_name='Categoría'),
        ),
    ]
