# Generated by Django 3.2.3 on 2022-10-05 23:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrator', '0012_alter_food_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id_order', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Fecha')),
                ('state', models.CharField(choices=[('PEND', 'Pendiente'), ('ENTR', 'Entregado'), ('CANC', 'Cancelado')], default='PEND', max_length=4)),
                ('pickup_time', models.TimeField(choices=[(1, datetime.time(11, 30)), (2, datetime.time(12, 0)), (3, datetime.time(12, 30)), (4, datetime.time(13, 0)), (5, datetime.time(13, 30))], default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
