# Generated by Django 3.2.3 on 2022-10-05 23:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0013_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.AddField(
            model_name='order',
            name='date_time',
            field=models.DateField(default=datetime.datetime(2022, 10, 5, 20, 42, 57, 313687), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_time',
            field=models.TimeField(choices=[(1, datetime.time(11, 30)), (2, datetime.time(12, 0)), (3, datetime.time(12, 30)), (4, datetime.time(13, 0)), (5, datetime.time(13, 30))], default=1, verbose_name='Hora de retiro'),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('PEND', 'Pendiente'), ('ENTR', 'Entregado'), ('CANC', 'Cancelado')], default='PEND', max_length=4, verbose_name='Estado'),
        ),
    ]
