# Generated by Django 3.2.3 on 2022-10-06 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0016_auto_20221005_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderfood',
            name='food',
        ),
        migrations.RemoveField(
            model_name='orderfood',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderFood',
        ),
    ]
