# Generated by Django 3.2.3 on 2022-11-12 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0017_auto_20221006_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.FloatField(default=100, verbose_name='Precio'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PriceFood',
        ),
    ]
